# Generated by Django 2.1.3 on 2018-11-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=9)),
                ('horario', models.DateTimeField()),
                ('sala', models.CharField(max_length=20)),
            ],
        ),
    ]
