# Generated by Django 2.1.3 on 2018-11-26 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('PALESTRA', 'Palestra'), ('MINICURSO', 'Minicurso')], default='MINICURSO', max_length=9)),
                ('horario', models.DateTimeField()),
                ('sala', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacao.Pessoa'),
        ),
    ]
